source 'https://github.com/HeQiang-IOS/HQRepo.git'
source 'https://cdn.cocoapods.org/'
use_frameworks!

platform :ios, '9.0'

target 'Haizeiwang_Example' do
  pod 'Haizeiwang', :path => '../'

  target 'Haizeiwang_Tests' do
    inherit! :search_paths

    
  end
end
